table klant
	lineageTag: c5307b43-7b51-4d60-bac6-7a8ece5534bd

	column key
		dataType: string
		lineageTag: da6be98c-1229-4ea4-98ee-bff32016f105
		summarizeBy: none
		sourceColumn: key

		changedProperty = DataType

		annotation SummarizationSetBy = Automatic

	column 'klant achternaam'
		dataType: string
		lineageTag: 33e7a309-6ca7-4b54-98b5-973f59dcb4dd
		summarizeBy: none
		sourceColumn: klant naam

		annotation SummarizationSetBy = Automatic

	column gender
		dataType: string
		lineageTag: 18f33a75-1472-487c-8eb7-d96ebda3e047
		summarizeBy: none
		sourceColumn: gender

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	column plaats
		dataType: string
		lineageTag: 7f69fc85-2262-47fc-b137-8a08083a1510
		summarizeBy: none
		sourceColumn: plaats

		annotation SummarizationSetBy = Automatic

	partition klant-3af0a4fa-810b-46ac-a356-877a4f1d3f85 = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(File.Contents("C:\PBI\PBIX oefen per onderwerp\Oefen eigen bron.xlsx"), null, true),
				    klant_Table = Source{[Item="klant",Kind="Table"]}[Data],
				    #"Changed Type" = Table.TransformColumnTypes(klant_Table,{{"key", Int64.Type}, {"naam", type text}, {"gender", type text}, {"plaats", type text}}),
				    #"Renamed Columns" = Table.RenameColumns(#"Changed Type",{{"naam", "klant naam"}})
				in
				    #"Renamed Columns"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

